name: release

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PYTHON_ENV: ci
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      QMBOT_TOKEN: ${{ secrets.QMBOT_TOKEN }}

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev dependencies
        run: make install
      - name: Lint
        run: make lint
      - name: test version
        run: make version
      - name: publish
        if: ${{ matrix.python-version == '3.11' && github.event.head_commit.message == 'release' }}
        run: make publish
